repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(deprecated_javascript_version/|errors_py/|logs/)
      - id: end-of-file-fixer
        exclude: ^(deprecated_javascript_version/|errors_py/|logs/)
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(deprecated_javascript_version/|errors_py/|logs/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        exclude: ^(deprecated_javascript_version/|errors_py/|logs/)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^(deprecated_javascript_version/|errors_py/|logs/)
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: ^(deprecated_javascript_version/|errors_py/|logs/|tests/)
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports, --no-strict-optional]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest --co -q
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
